services:

  _defaults:
    public: true

  rikudou_cron.logger:
    alias: 'logger'

  Rikudou\CronBundle\Command\:
    resource: '../../Command'
    tags: [console.command]

  Rikudou\CronBundle\Cron\CronJobsList: ~
