services:

  rikudou.cron.cron_job_list:
    class: Rikudou\CronBundle\Cron\CronJobList

  rikudou.cron.command.list:
    class: Rikudou\CronBundle\Command\ListCronJobsCommand
    arguments:
      ['@rikudou.cron.cron_job_list']
    tags:
      - console.command

  rikudou.cron.command.run:
    class: Rikudou\CronBundle\Command\RunCronJobsCommand
    arguments:
      ['@rikudou.cron.cron_job_list']
    tags:
      - console.command
    calls:
      - [setLogger, ['@?rikudou.cron.logger']]
      - [setEventDispatcher, ['@?event_dispatcher']]

  rikudou.cron.command.execute:
    class: Rikudou\CronBundle\Command\ExecuteCronJobCommand
    arguments:
      ['@rikudou.cron.cron_job_list']
    tags:
      - console.command
    calls:
      - [setLogger, ['@?rikudou.cron.logger']]
